require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - '.git/**/*'
    - 'Guardfile'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'config/application.rb'
    - 'config/puma.rb'
    - 'config/environments/*.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'log/*'
    - 'tmp/**/*'
    - 'storage/**/*'
    - 'vendor/**/*'
    - '.sass-cache/**/*'
    - 'coverage/**/*'
    - 'public/**/*'

Rails/SaveBang:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  Max: 45
  ExcludedMethods:
    - refine
    - guard
    - describe
    - context
    - namespace

Layout/LineLength:
  Max: 120

Lint/RaiseException:
  Enabled: true

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: false

Style/SlicingWithRange:
  Enabled: true

# CUSTOM
Rails/Output:
  Enabled: false
